# Stage 3 - Data Understanding and Exploratory Data Analysis

## 1. Import Required Libraries

This notebook performs initial investigation of the wildfire dataset
before applying preprocessing techniques.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment ready")

Environment ready

# Stage 3 - Data Understanding and Exploratory Data Analysis

## 1. Dataset Loading

The raw wildfire dataset is loaded without modification.
The purpose of this stage is to understand the dataset before
performing preprocessing.

In [4]:
DATA_PATH = "../../data/raw/Wildfire_Dataset.csv"

df = pd.read_csv(DATA_PATH)

In [5]:
df.head(5)

,latitude,longitude,datetime,Wildfire,pr,rmax,rmin,sph,srad,tmmn,tmmx,vs,bi,fm100,fm1000,erc,etr,pet,vpd
0,48.128431,-97.276685,2018-08-15,No,0.0,78.6,14.9,0.00582,272.6,282.0,301.6,3.0,40.0,10.2,12.2,54.0,7.5,5.5,1.59
1,48.128431,-97.276685,2018-08-16,No,0.0,80.4,13.9,0.00676,264.0,283.9,304.9,3.0,40.0,9.7,12.0,56.0,8.2,5.9,1.93
2,48.128431,-97.276685,2018-08-17,No,0.0,70.9,20.4,0.00672,265.6,285.8,300.7,3.1,40.0,9.2,11.9,56.0,7.2,5.3,1.51
3,48.128431,-97.276685,2018-08-18,No,5.0,65.2,19.4,0.00756,261.4,289.0,303.3,5.1,0.0,9.9,12.0,40.0,10.0,6.9,1.85
4,48.128431,-97.276685,2018-08-19,No,0.0,100.0,42.2,0.00895,166.8,283.8,296.5,4.7,41.0,11.8,12.1,47.0,4.6,3.4,0.66

In [6]:
df.shape

(9509925, 19)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9509925 entries, 0 to 9509924
Data columns (total 19 columns):
 #   Column     Dtype
---  ------     -----
 0   latitude   float64
 1   longitude  float64
 2   datetime   str
 3   Wildfire   str
 4   pr         float64
 5   rmax       float64
 6   rmin       float64
 7   sph        float64
 8   srad       float64
 9   tmmn       float64
 10  tmmx       float64
 11  vs         float64
 12  bi         float64
 13  fm100      float64
 14  fm1000     float64
 15  erc        float64
 16  etr        float64
 17  pet        float64
 18  vpd        float64
dtypes: float64(17), str(2)
memory usage: 1.3 GB

In [9]:
#check for missing values
df.isnull().sum()

latitude     0
longitude    0
datetime     0
Wildfire     0
pr           0
rmax         0
rmin         0
sph          0
srad         0
tmmn         0
tmmx         0
vs           0
bi           0
fm100        0
fm1000       0
erc          0
etr          0
pet          0
vpd          0
dtype: int64

In [11]:
#duplicate record analysis
df.duplicated().sum()

np.int64(13920)

In [12]:
df[df.duplicated()].head()

,latitude,longitude,datetime,Wildfire,pr,rmax,rmin,sph,srad,tmmn,tmmx,vs,bi,fm100,fm1000,erc,etr,pet,vpd
155775,33.90551,-118.1835,2020-11-09,No,0.0,80.9,35.9,0.00471,184.3,279.5,289.2,2.1,28.0,15.6,14.4,39.0,2.9,2.1,0.63
155776,33.90551,-118.1835,2020-11-10,No,0.0,74.3,27.7,0.00457,182.5,280.4,291.9,1.9,29.0,14.1,14.3,42.0,3.2,2.3,0.85
155777,33.90551,-118.1835,2020-11-11,No,0.0,84.5,34.1,0.00536,180.3,280.7,291.9,1.5,27.0,13.9,14.3,41.0,2.6,2.0,0.73
155778,33.90551,-118.1835,2020-11-12,No,0.0,97.7,38.1,0.00652,165.1,281.3,293.6,1.2,24.0,15.1,14.6,38.0,2.3,1.8,0.69
155779,33.90551,-118.1835,2020-11-13,No,0.0,95.9,44.8,0.00670,165.5,282.0,291.9,1.6,25.0,15.9,14.6,36.0,2.3,1.8,0.56

In [23]:
df.value_counts().head()

latitude  longitude  datetime    Wildfire  pr   rmax  rmin  sph      srad   tmmn   tmmx   vs   bi    fm100  fm1000  erc   etr  pet  vpd
33.90551  -118.1835  2020-11-09  No        0.0  80.9  35.9  0.00471  184.3  279.5  289.2  2.1  28.0  15.6   14.4    39.0  2.9  2.1  0.63    4
                     2020-11-10  No        0.0  74.3  27.7  0.00457  182.5  280.4  291.9  1.9  29.0  14.1   14.3    42.0  3.2  2.3  0.85    4
                     2020-11-11  No        0.0  84.5  34.1  0.00536  180.3  280.7  291.9  1.5  27.0  13.9   14.3    41.0  2.6  2.0  0.73    4
                     2020-11-12  No        0.0  97.7  38.1  0.00652  165.1  281.3  293.6  1.2  24.0  15.1   14.6    38.0  2.3  1.8  0.69    4
                     2020-11-13  No        0.0  95.9  44.8  0.00670  165.5  282.0  291.9  1.6  25.0  15.9   14.6    36.0  2.3  1.8  0.56    4
Name: count, dtype: int64

# Phase 4 — Target Variable Analysis

## Objective

Analyze the distribution of the target variable (`Wildfire`) to
understand the prediction problem and identify whether class imbalance
exists.

In [24]:
df["Wildfire"].value_counts()

Wildfire
No     9007860
Yes     502065
Name: count, dtype: int64

# Phase 5 — Data Type Analysis

## Objective

Identify the data types of all attributes in the wildfire dataset and
categorize features into numerical, categorical, date/time, and target
variables.

In [25]:
# Display the data type of each column
df.dtypes

latitude     float64
longitude    float64
datetime         str
Wildfire         str
pr           float64
rmax         float64
rmin         float64
sph          float64
srad         float64
tmmn         float64
tmmx         float64
vs           float64
bi           float64
fm100        float64
fm1000       float64
erc          float64
etr          float64
pet          float64
vpd          float64
dtype: object

# Phase 06 — Statistical Summary Analysis

## Objective

Analyze the statistical characteristics of numerical features to understand
their distribution, range, variation, and identify potential abnormal
values that may require further investigation during preprocessing.

In [26]:
# Generate statistical summary for numerical features
df.describe().T

,count,mean,std,min,25%,50%,75%,max
latitude,9509925.0,39.143615,5.267332,25.26027,34.68867,38.531610,43.670042,48.99873
longitude,9509925.0,-106.434732,14.569240,-124.43700,-118.34392,-110.925833,-95.419900,-67.01250
pr,9509925.0,90.368911,1701.835716,0.00000,0.00000,0.000000,0.000000,32767.00000
rmax,9509925.0,164.575421,1698.086057,5.00000,61.80000,80.000000,95.200000,32767.00000
rmin,9509925.0,122.070653,1700.271804,1.00000,19.30000,30.800000,45.500000,32767.00000
sph,9509925.0,88.643039,1701.913860,0.00013,0.00360,0.005520,0.007790,32767.00000
srad,9509925.0,309.158711,1692.716566,0.00000,147.20000,227.700000,300.100000,32767.00000
tmmn,9509925.0,368.213687,1687.376228,230.90000,274.90000,281.100000,286.400000,32767.00000
tmmx,9509925.0,382.141498,1686.659227,241.90000,287.90000,295.500000,301.900000,32767.00000
vs,9509925.0,92.391416,1701.719467,0.30000,2.60000,3.400000,4.600000,32767.00000
bi,9509925.0,122.166778,1700.336089,0.00000,19.00000,34.000000,50.000000,32767.00000
fm100,9509925.0,101.389205,1701.257210,1.10000,8.70000,12.900000,16.600000,32767.00000
fm1000,9509925.0,103.098557,1701.168985,2.10000,10.30000,14.800000,18.400000,32767.00000
erc,9509925.0,132.092236,1699.822144,0.00000,25.00000,39.000000,61.000000,32767.00000
etr,9509925.0,94.255985,1701.624325,0.00000,3.20000,5.400000,7.700000,32767.00000
pet,9509925.0,92.755266,1701.701158,0.00000,2.30000,4.100000,5.800000,32767.00000
vpd,9509925.0,89.765462,1701.855632,0.00000,0.47000,0.920000,1.580000,32767.00000

In [27]:
# Check how many records contain the possible sentinel value 32767
(df == 32767).sum()

latitude         0
longitude        0
datetime         0
Wildfire         0
pr           25725
rmax         25725
rmin         25725
sph          25725
srad         25725
tmmn         25725
tmmx         25725
vs           25725
bi           25725
fm100        25725
fm1000       25725
erc          25725
etr          25725
pet          25725
vpd          25725
dtype: int64

In [28]:
# Check rows where weather data is unavailable
df[df["pr"] == 32767].head()

,latitude,longitude,datetime,Wildfire,pr,rmax,rmin,sph,srad,tmmn,tmmx,vs,bi,fm100,fm1000,erc,etr,pet,vpd
29100,42.062601,-80.953609,2017-11-17,No,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0
29101,42.062601,-80.953609,2017-11-18,No,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0
29102,42.062601,-80.953609,2017-11-19,No,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0
29103,42.062601,-80.953609,2017-11-20,No,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0
29104,42.062601,-80.953609,2017-11-21,No,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0,32767.0

In [29]:
# Check rows where all environmental variables contain the sentinel value
weather_columns = [
    "pr", "rmax", "rmin", "sph", "srad",
    "tmmn", "tmmx", "vs", "bi",
    "fm100", "fm1000", "erc", "etr",
    "pet", "vpd"
]

(df[weather_columns] == 32767).all(axis=1).sum()

np.int64(25725)

# Phase 07 — Outlier Analysis

## Objective

Identify extreme values within numerical features and determine whether
they represent data errors or valid environmental conditions relevant to
wildfire prediction.

In [30]:
# Generate percentile values to identify extreme ranges
df.select_dtypes(include="number").quantile(
    [0.01, 0.05, 0.95, 0.99]
).T

                0.01        0.05        0.95        0.99
latitude    28.12528   31.426716   47.977585   48.740100
longitude -123.65250 -122.377751  -79.170000  -69.662982
pr           0.00000    0.000000   10.700000   34.900000
rmax        25.10000   36.700000  100.000000  100.000000
rmin         4.00000    8.500000   68.200000   85.900000
sph          0.00104    0.001880    0.012870    0.017410
srad        42.30000   73.500000  348.000000  364.600000
tmmn       255.20000  265.400000  293.800000  297.900000
tmmx       267.00000  275.700000  309.000000  313.700000
vs           1.20000    1.700000    7.100000    9.500000
bi           0.00000    0.000000   75.000000   97.000000
fm100        3.70000    5.100000   20.900000   24.400000
fm1000       4.60000    6.200000   22.600000   27.500000
erc          1.00000   11.000000   88.000000  101.000000
etr          0.40000    1.100000   11.200000   14.300000
pet          0.30000    0.800000    8.000000    9.800000
vpd          0.00000    0.120000    2.910000    4.160000

In [31]:
# Calculate IQR boundaries for maximum temperature
Q1 = df["tmmx"].quantile(0.25)
Q3 = df["tmmx"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

lower_bound, upper_bound

(np.float64(266.9), np.float64(322.9))

In [32]:
# Calculate IQR boundaries for wind speed
Q1 = df["vs"].quantile(0.25)
Q3 = df["vs"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

lower_bound, upper_bound

(np.float64(-0.399999999999999), np.float64(7.599999999999999))

# Phase 08 — Feature Engineering Preparation

## Objective

Transform raw date/time information into meaningful features that can
capture seasonal and temporal patterns related to wildfire occurrence.

In [33]:
# Check the current datatype of datetime column
df["datetime"].dtype

In [34]:
# Convert datetime column from string to datetime format
df["datetime"] = pd.to_datetime(df["datetime"])

In [35]:
# Confirm the datatype after conversion
df["datetime"].dtype

dtype('<M8[us]')

In [36]:
# Check the time period covered by the dataset
df["datetime"].agg(["min", "max"])

min   2013-12-31
max   2025-04-13
Name: datetime, dtype: datetime64[us]

In [37]:
# Check wildfire distribution across months
df.groupby(
    df["datetime"].dt.month
)["Wildfire"].value_counts()

datetime  Wildfire
1         No          572367
          Yes          31731
2         No          645730
          Yes          31299
3         No          809215
          Yes          36435
4         No          808832
          Yes          39930
5         No          877966
          Yes          44039
6         No          920754
          Yes          46952
7         No          975637
          Yes          52842
8         No          905250
          Yes          52211
9         No          778979
          Yes          46890
10        No          688271
          Yes          44446
11        No          535556
          Yes          40254
12        No          489303
          Yes          35036
Name: count, dtype: int64

# Phase 09 — Feature Relationship Analysis

## Objective

Analyze relationships between numerical features and the target variable to
identify useful predictors, understand feature dependencies, and detect
highly correlated attributes.

In [38]:
# Create temporary numerical target for correlation analysis
df["Wildfire_encoded"] = df["Wildfire"].map(
    {"No": 0, "Yes": 1}
)

In [39]:
# Check the new encoded target values
df[["Wildfire", "Wildfire_encoded"]].head()

  Wildfire  Wildfire_encoded
0       No                 0
1       No                 0
2       No                 0
3       No                 0
4       No                 0

In [40]:
# Calculate correlation between numerical features and wildfire occurrence
correlation = df.select_dtypes(include="number").corr()["Wildfire_encoded"].sort_values(ascending=False)

correlation

Wildfire_encoded    1.000000
erc                -0.011491
bi                 -0.011754
tmmx               -0.012093
tmmn               -0.012130
etr                -0.012253
pet                -0.012271
vpd                -0.012276
sph                -0.012296
vs                 -0.012313
srad               -0.012319
pr                 -0.012321
fm100              -0.012422
fm1000             -0.012503
rmin               -0.012672
rmax               -0.012689
latitude           -0.030539
longitude          -0.051478
Name: Wildfire_encoded, dtype: float64

In [41]:
# Check correlation between numerical features
feature_correlation = df.select_dtypes(include="number").drop(
    columns=["Wildfire_encoded"]
).corr()

feature_correlation

,latitude,longitude,pr,rmax,rmin,sph,srad,tmmn,tmmx,vs,bi,fm100,fm1000,erc,etr,pet,vpd
latitude,1.000000,-0.049644,0.060371,0.061846,0.061560,0.060448,0.060927,0.058872,0.058896,0.060512,0.058383,0.060690,0.060898,0.058194,0.060217,0.060301,0.060353
longitude,-0.049644,1.000000,0.072715,0.076203,0.075728,0.072250,0.056825,0.071282,0.070659,0.072488,0.067686,0.073458,0.073700,0.065615,0.071720,0.071864,0.072072
pr,0.060371,0.072715,1.000000,0.999927,0.999949,0.999993,0.998596,0.999980,0.999972,0.999993,0.999874,0.999992,0.999991,0.999876,0.999990,0.999991,0.999993
rmax,0.061846,0.076203,0.999927,1.000000,0.999965,0.999925,0.998353,0.999896,0.999881,0.999926,0.999716,0.999950,0.999946,0.999688,0.999911,0.999916,0.999921
rmin,0.061560,0.075728,0.999949,0.999965,1.000000,0.999942,0.998312,0.999917,0.999889,0.999944,0.999741,0.999963,0.999959,0.999721,0.999927,0.999932,0.999938
sph,0.060448,0.072250,0.999993,0.999925,0.999942,1.000000,0.998649,0.999987,0.999982,1.000000,0.999901,0.999996,0.999995,0.999899,0.999998,0.999999,1.000000
srad,0.060927,0.056825,0.998596,0.998353,0.998312,0.998649,1.000000,0.998778,0.998842,0.998640,0.998889,0.998556,0.998565,0.998950,0.998721,0.998706,0.998665
tmmn,0.058872,0.071282,0.999980,0.999896,0.999917,0.999987,0.998778,1.000000,0.999996,0.999985,0.999905,0.999976,0.999976,0.999915,0.999991,0.999990,0.999988
tmmx,0.058896,0.070659,0.999972,0.999881,0.999889,0.999982,0.998842,0.999996,1.000000,0.999980,0.999918,0.999967,0.999967,0.999930,0.999989,0.999987,0.999984
vs,0.060512,0.072488,0.999993,0.999926,0.999944,1.000000,0.998640,0.999985,0.999980,1.000000,0.999901,0.999996,0.999995,0.999896,0.999998,0.999999,0.999999
bi,0.058383,0.067686,0.999874,0.999716,0.999741,0.999901,0.998889,0.999905,0.999918,0.999901,1.000000,0.999867,0.999866,0.999969,0.999916,0.999911,0.999905
fm100,0.060690,0.073458,0.999992,0.999950,0.999963,0.999996,0.998556,0.999976,0.999967,0.999996,0.999867,1.000000,0.999999,0.999857,0.999990,0.999992,0.999995
fm1000,0.060898,0.073700,0.999991,0.999946,0.999959,0.999995,0.998565,0.999976,0.999967,0.999995,0.999866,0.999999,1.000000,0.999854,0.999990,0.999992,0.999994
erc,0.058194,0.065615,0.999876,0.999688,0.999721,0.999899,0.998950,0.999915,0.999930,0.999896,0.999969,0.999857,0.999854,1.000000,0.999916,0.999911,0.999905
etr,0.060217,0.071720,0.999990,0.999911,0.999927,0.999998,0.998721,0.999991,0.999989,0.999998,0.999916,0.999990,0.999990,0.999916,1.000000,1.000000,0.999999
pet,0.060301,0.071864,0.999991,0.999916,0.999932,0.999999,0.998706,0.999990,0.999987,0.999999,0.999911,0.999992,0.999992,0.999911,1.000000,1.000000,1.000000
vpd,0.060353,0.072072,0.999993,0.999921,0.999938,1.000000,0.998665,0.999988,0.999984,0.999999,0.999905,0.999995,0.999994,0.999905,0.999999,1.000000,1.000000

 Phase 10 — Data Leakage Analysis

## Objective

Identify potential data leakage risks by examining whether any attributes
contain information that would not be available during real-world wildfire
prediction.

In [44]:
# Display all dataset columns for leakage inspection
df.columns.tolist()

['latitude',
 'longitude',
 'datetime',
 'Wildfire',
 'pr',
 'rmax',
 'rmin',
 'sph',
 'srad',
 'tmmn',
 'tmmx',
 'vs',
 'bi',
 'fm100',
 'fm1000',
 'erc',
 'etr',
 'pet',
 'vpd',
 'Wildfire_encoded']

In [45]:
# Check number of observations available for each year
df["datetime"].dt.year.value_counts().sort_index()

datetime
2013         49
2014    1213318
2015    1240064
2016    1160796
2017    1080744
2018     970501
2019     875890
2020     799530
2021     718859
2022     617160
2023     491430
2024     322374
2025      19210
Name: count, dtype: int64